apiVersion: v1
kind: ServiceAccount
metadata:
  name: restaurant-app-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restaurant-app-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restaurant-app-rolebinding
subjects:
  - kind: ServiceAccount
    name: restaurant-app-sa
roleRef:
  kind: Role
  name: restaurant-app-role
  apiGroup: rbac.authorization.k8s.io